### ISSUE TITLE
jQuery not defined error in the recorder although pages load fine in Chrome 

### ISSUE THREAD

**Issue by Nikschavan** [dsheiko/puppetry#33]
Here is a screenshot of trying to open WordPress customizer in the recorder - 

![image](https://user-images.githubusercontent.com/2931091/62422522-9eca7800-b6d1-11e9-96de-56ff3162328e.png)

The page loads correctly in Google Chrome - 

![image](https://user-images.githubusercontent.com/2931091/62422537-c28dbe00-b6d1-11e9-95aa-ae7911538446.png)

Any ideas why this must be happening and how it can be fixed?

**Comment by dsheiko** [comment]
Thanks for reporting. A good one BTW. jQuery doesn't load because it's implemented as UMD, but since I have enabled node integration for webview with tst site it gets confused. It thinks that it's on Node.js env. I made the fix for 2.0.3, but will deploy it a week or so (in case a new issue to include them also).  YEt I don't want to block you, so you can get the 2.0.3 RC already by the link

- Windows: https://drive.google.com/open?id=158CL_xQKj8D_bPaWk414XswQRG51MR1Q
- Linux: https://drive.google.com/open?id=10Opv-cQCXgvcgevPzDEiFZvot-UIoFt2
- Mac: https://drive.google.com/open?id=1EKJHO7jGUucv5YPrI3bu64H_Ck1bmbEt
