### ISSUE TITLE
Getting "Duplicate declaration target error "

### ISSUE THREAD

**Issue by monika-12** [dsheiko/puppetry#35]
I am running the project on the latest release with new suite but still getting the same error - Duplicate declaration "A_CLASS_AB_ITEM"

**Steps to Reproduce the Issue**
1. Create a New project and suite
2. Create a test case with the selector you used previously
3. Run the Testcase
4. Try with Manual and Record

**Actual:** Will get an error of the "Duplicate Declaration" because The targets from recording landed on top of the same targets from the previous recording.

**Expected:** Error should not display. Normally Selectors should get new unique names every time.

Screeenshot - `https://cl.ly/d03ca59bb9d6`

Project File - 
[Test-1.zip](https://github.com/dsheiko/puppetry/files/3488600/Test-1.zip)

**Comment by dsheiko** [comment]
Thank you, gonna check on Monday

**Comment by dsheiko** [comment]
You were right, I messed up on merging targets of the suite and of snippets. The fix will be available in v2.0.4. I plan to release in a week, but you can take already the RC

https://drive.google.com/open?id=1S7YixYpRWXiFcL4XAvRdQET1jLTZkDlm

As for your test, you were missing login scenario. Puppetry starts tests in incognito mode. So if you logged in in one suite, it doesn't mean you still logged in in the other. That's why I introduced the Snippets in 2.0.0.

**Comment by monika-12** [comment]
Thanks for the quick fix.

**Comment by dsheiko** [comment]
I believe the fix is live https://github.com/dsheiko/puppetry/releases/tag/v2.0.4
